const RX = [
  {id:1,name:"Chicken Tikka Masala",e:"🍗",t:50,k:380,p:44,c:14,f:14,batch:4,
   desc:"The classic — cook Sunday, eat Mon–Thu. Rich tomato-yogurt gravy.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Low-fat Greek yogurt",a:"150g (marinade)",cat:"dairy",pr:0.54},
    {n:"Onions",a:"2 large",cat:"veg",pr:0.36},
    {n:"Tomatoes",a:"4 medium",cat:"veg",pr:0.60},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp grated",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Cumin powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Mild paprika",a:"1 tsp",cat:"dry",pr:0.05},
   ],
   steps:[
    "MARINATE: Cube chicken (bite-size). Mix with yogurt + all spices + half the garlic. Marinate 30 min minimum, overnight is better.",
    "OVEN (optional but better): Spread on foil-lined tray, 220°C, 18 min until edges char. Set aside.",
    "GRAVY BASE: Heat oil in large pot. Add diced onion, cook 8 min until deep golden — don't rush this.",
    "Add remaining garlic + ginger paste. Cook 2 min stirring.",
    "Add chopped tomatoes. Cook 10 min on medium until very thick, oil starts separating.",
    "Add chicken (+ any juices). Add 200ml water. Simmer 10 min.",
    "PORTION: Divide into 4 containers (roughly 250g each). Refrigerate — tastes better day 2 onward.",
    "SERVE: Reheat each portion, eat with 60–80g dry weight rice or alone.",
   ]},
  {id:2,name:"Murgh Makhani (No-Cream)",e:"🧡",t:50,k:350,p:42,c:16,f:13,batch:4,
   desc:"Butter chicken without the cream — same depth, half the calories.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Low-fat Greek yogurt",a:"120g (marinade)",cat:"dairy",pr:0.43},
    {n:"Onions",a:"2 large",cat:"veg",pr:0.36},
    {n:"Tomatoes",a:"5 medium",cat:"veg",pr:0.75},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Butter",a:"1 tsp (for flavour only)",cat:"dairy",pr:0.05},
    {n:"Olive oil",a:"1 tsp",cat:"dry",pr:0.04},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Cumin powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Mild paprika",a:"2 tsp (gives the colour)",cat:"dry",pr:0.08},
   ],
   steps:[
    "MARINATE: Cube chicken, coat in yogurt + turmeric + 1 tsp cumin + 1 tsp coriander. Rest 30+ min.",
    "GRILL/OVEN: 220°C, 18 min on foil tray until slightly charred. Set aside.",
    "SAUCE: Melt butter + oil. Add onions, cook 8 min golden.",
    "Add garlic + ginger, cook 2 min.",
    "Add tomatoes + remaining spices + paprika. Cook 12 min until very thick — blend with hand blender if you want smooth sauce.",
    "Add chicken + 150ml water. Simmer 10 min.",
    "PORTION: 4 equal containers. This sauce gets deeper on day 2–3.",
   ]},
  {id:3,name:"Chicken Bhuna",e:"🌶️",t:40,k:310,p:43,c:10,f:11,batch:4,
   desc:"Dry-ish, intense curry — spices cling to the chicken. Best reheated.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Onions",a:"3 large",cat:"veg",pr:0.54},
    {n:"Tomatoes",a:"3 medium",cat:"veg",pr:0.45},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Cumin seeds",a:"2 tsp (whole)",cat:"dry",pr:0.08},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Mild paprika",a:"1 tsp",cat:"dry",pr:0.05},
   ],
   steps:[
    "Heat oil on HIGH. Add whole cumin seeds — sizzle 15 sec.",
    "Add onion. Cook 10 min on high, stirring often, until dark golden/slightly charred at edges.",
    "Add garlic + ginger paste. Cook 2 min.",
    "Add turmeric, coriander, paprika. Stir 1 min — spices bloom in hot pan.",
    "Add chicken (cubed). Stir to coat. Cook 5 min sealing all sides.",
    "Add tomatoes. Cook 8 min, stirring often — bhuna means 'keep frying'.",
    "Add 100ml water only if sticking. Cook until almost dry. Season heavily.",
    "PORTION: 4 containers. Works great with Greek yogurt on the side.",
   ]},
  {id:4,name:"Chicken Saag",e:"🥬",t:40,k:290,p:46,c:8,f:10,batch:4,
   desc:"Chicken in spiced spinach — highest protein batch, lowest carb.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Frozen spinach",a:"400g",cat:"veg",pr:0.99},
    {n:"Onion",a:"1 large",cat:"veg",pr:0.18},
    {n:"Tomatoes",a:"3 medium",cat:"veg",pr:0.45},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Turmeric",a:"1½ tsp",cat:"dry",pr:0.07},
    {n:"Cumin seeds",a:"1 tsp",cat:"dry",pr:0.04},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
   ],
   steps:[
    "SPINACH BASE: Defrost spinach, squeeze out ALL water. Blend or finely chop.",
    "Heat oil, sizzle cumin. Add onion, cook 5 min.",
    "Add garlic + ginger, 2 min. Add tomatoes + turmeric + coriander, cook 6 min.",
    "Add chicken cubes. Brown all sides, 5 min.",
    "Add spinach. Stir well. Add 100ml water.",
    "Cover and simmer 15 min. Uncover, cook 5 min to dry out slightly.",
    "Season. PORTION: 4 containers — green colour is iron and protein.",
   ]},
  {id:5,name:"Kadhai Chicken",e:"🫑",t:35,k:330,p:44,c:12,f:12,batch:4,
   desc:"Chicken with peppers kadhai style — colourful, fast, satisfying.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Bell peppers",a:"3 (mixed colours)",cat:"veg",pr:1.47},
    {n:"Onions",a:"2 large",cat:"veg",pr:0.36},
    {n:"Tomatoes",a:"4 medium",cat:"veg",pr:0.60},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Cumin seeds",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
   ],
   steps:[
    "Cube chicken. Chop peppers into 3cm chunks.",
    "Heat oil on high. Sizzle cumin 10 sec.",
    "Add onion, cook 5 min. Add garlic + ginger, 2 min.",
    "Add chicken. Stir-fry on high 6 min until sealed.",
    "Add tomatoes + spices. Cook 6 min.",
    "Add peppers. Cook 8 min — keep some crunch in peppers.",
    "Season well. PORTION: 4 containers.",
   ]},
  {id:6,name:"Dahi Wala Chicken",e:"🤍",t:45,k:340,p:46,c:9,f:14,batch:4,
   desc:"Yogurt-braised — silky, mild, great with rice. Most forgiving recipe.",
   ing:[
    {n:"Chicken thighs (boneless)",a:"800g (more flavour than breast for braising)",cat:"protein",pr:4.29},
    {n:"Low-fat Greek yogurt",a:"200g",cat:"dairy",pr:0.72},
    {n:"Onions",a:"2 large",cat:"veg",pr:0.36},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Cumin powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
   ],
   steps:[
    "IMPORTANT: Whisk yogurt well before adding — lumpy yogurt = split sauce.",
    "Heat oil. Cook sliced onion 8 min until deep golden.",
    "Add garlic + ginger paste. Cook 2 min.",
    "Add spices, stir 1 min.",
    "Add chicken thighs whole. Brown both sides, 4 min.",
    "Reduce to LOW heat. Add whisked yogurt. Stir gently to coat everything.",
    "Cover and simmer 18 min on very low — don't boil or yogurt splits.",
    "Uncover, cook 5 min to thicken. Season. PORTION: 4 containers.",
   ]},
  {id:7,name:"Chicken Do Pyaza",e:"🧅",t:50,k:320,p:43,c:14,f:11,batch:4,
   desc:"Double onion curry — onions added twice for depth and sweetness.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Onions",a:"4 large (double onion = do pyaza)",cat:"veg",pr:0.72},
    {n:"Tomatoes",a:"3 medium",cat:"veg",pr:0.45},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Cumin seeds",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Black pepper",a:"1 tsp cracked",cat:"dry",pr:0.04},
   ],
   steps:[
    "Slice 2 onions thin. Dice the other 2 onions.",
    "Heat oil, sizzle cumin. Add DICED onions. Cook 8 min until golden.",
    "Add garlic + ginger. Cook 2 min. Add tomatoes + spices. Cook 8 min.",
    "Add chicken (cubed). Brown 5 min.",
    "Add SLICED onions now (the 'second' addition). Stir well.",
    "Add 150ml water. Simmer covered 15 min.",
    "Uncover, cook 5 min until sauce thickens. Season. PORTION: 4 containers.",
   ]},
  {id:8,name:"Chicken Keema Style",e:"🥩",t:30,k:300,p:42,c:10,f:11,batch:5,
   desc:"Minced-style chicken with peas — fastest cook, 5 portions, lowest cost.",
   ing:[
    {n:"Chicken breast",a:"800g (dice very small, 5mm cubes)",cat:"protein",pr:5.49},
    {n:"Onions",a:"2 large",cat:"veg",pr:0.36},
    {n:"Tomatoes",a:"4 medium",cat:"veg",pr:0.60},
    {n:"Bell pepper",a:"1",cat:"veg",pr:0.50},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Cumin seeds",a:"1 tsp",cat:"dry",pr:0.04},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
   ],
   steps:[
    "Dice chicken into 5mm cubes — this is key, makes it cook fast and absorb spices.",
    "Heat oil. Sizzle cumin. Add onion + pepper, cook 4 min.",
    "Add garlic + ginger, 1 min.",
    "Add chicken. Cook on HIGH stirring constantly — 5 min.",
    "Add tomatoes + all spices. Cook 8 min until thick and dry.",
    "No water needed — very little sauce, almost dry. Season generously.",
    "PORTION: 5 containers. Works great with egg bhurji on the side.",
   ]},
  {id:9,name:"Afghani Chicken",e:"🤍",t:45,k:360,p:45,c:8,f:16,batch:4,
   desc:"Mild golden yogurt curry — completely different flavour profile, no tomato.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Low-fat Greek yogurt",a:"200g (heavy marinade)",cat:"dairy",pr:0.72},
    {n:"Onion",a:"1 large",cat:"veg",pr:0.18},
    {n:"Garlic",a:"10 cloves (lots — it's Afghani)",cat:"veg",pr:0.25},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Turmeric",a:"½ tsp only (keep it pale/golden)",cat:"dry",pr:0.03},
    {n:"Cumin powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Black pepper",a:"1 tsp cracked",cat:"dry",pr:0.04},
   ],
   steps:[
    "MARINADE: Crush garlic into paste. Mix yogurt + garlic + ginger + all spices + black pepper. Season well.",
    "Cube chicken, coat completely in marinade. Marinate minimum 1 hour — overnight transforms it.",
    "OVEN CHAR: Spread on foil tray, 220°C, 20 min. You want golden-brown edges, not red.",
    "SAUCE: Heat oil, cook sliced onion until soft and golden — 6 min. Don't brown too dark.",
    "Add any remaining marinade + 100ml water. Stir and simmer 3 min.",
    "Add oven-cooked chicken + any resting juices. Simmer 8 min on low. Sauce will be pale, creamy-looking.",
    "Season generously with salt + extra black pepper. PORTION: 4 containers.",
    "NOTE: This is intentionally mild and aromatic — not spicy. Eat with rice or just the chicken alone.",
   ]},
  {id:10,name:"Chicken Handi",e:"🏺",t:55,k:370,p:44,c:14,f:14,batch:4,
   desc:"Deep slow-cooked pot curry — layers of spice, gets richer on day 3.",
   ing:[
    {n:"Chicken breast",a:"800g",cat:"protein",pr:5.49},
    {n:"Low-fat Greek yogurt",a:"150g",cat:"dairy",pr:0.54},
    {n:"Onions",a:"2 large",cat:"veg",pr:0.36},
    {n:"Tomatoes",a:"3 medium",cat:"veg",pr:0.45},
    {n:"Bell pepper",a:"1 (any colour)",cat:"veg",pr:0.50},
    {n:"Garlic",a:"8 cloves",cat:"veg",pr:0.20},
    {n:"Fresh ginger",a:"2 tsp",cat:"veg",pr:0.20},
    {n:"Olive oil",a:"2 tsp",cat:"dry",pr:0.07},
    {n:"Cumin seeds",a:"1 tsp (whole)",cat:"dry",pr:0.04},
    {n:"Turmeric",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Coriander powder",a:"2 tsp",cat:"dry",pr:0.08},
    {n:"Mild paprika",a:"1 tsp",cat:"dry",pr:0.05},
    {n:"Black pepper",a:"½ tsp",cat:"dry",pr:0.03},
   ],
   steps:[
    "LAYER 1 BASE: Heat oil in heavy pot. Add cumin seeds 10 sec. Add diced onion, cook 8 min until very golden.",
    "Add garlic + ginger paste, cook 3 min — longer than usual, really develop it.",
    "Add tomatoes + all dry spices. Cook 10 min on medium, stirring. Oil should separate clearly.",
    "LAYER 2 CHICKEN: Add chicken pieces. Brown each side 3 min — seal properly.",
    "LAYER 3 YOGURT: Whisk yogurt well. Reduce heat to LOW. Stir yogurt in slowly. Do NOT let it boil.",
    "Add diced bell pepper + 100ml water. Cover and simmer 20 min on very low heat.",
    "Uncover, cook 5 min to reduce sauce slightly. Season hard — handi needs salt.",
    "PORTION: 4 containers. Day 1 it is good. Day 2–3 it is excellent.",
   ]},
];
