-- Fix: editing an existing weigh-in (or any surrogate-id row addressed by a
-- natural key) failed forever.
--
-- weights/steps/sessions declared their surrogate primary key as
--   id bigint GENERATED ALWAYS AS IDENTITY
-- Postgres forbids inserting ANY explicit value into a GENERATED ALWAYS identity
-- column, and it enforces that while planning the INSERT — BEFORE the ON CONFLICT
-- clause of an upsert can turn the statement into an UPDATE. So the client's
-- "upsert today's weight" (which carries the existing row's id on every edit)
-- always errored with 428C9 "cannot insert a non-DEFAULT value into column id".
-- The very first weigh-in of a day (no id yet) worked; every correction failed.
--
-- GENERATED BY DEFAULT keeps auto-generation for fresh inserts (id omitted) but
-- permits an explicit id, so natural-key upserts resolve cleanly to an UPDATE.
-- The client also stops sending the surrogate id for these tables, so this is a
-- belt-and-braces correctness fix, not the sole line of defence.

alter table public.weights  alter column id set generated by default;
alter table public.steps    alter column id set generated by default;
alter table public.sessions alter column id set generated by default;
